// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.transport {
    public class VersionInfo {
        public static string appVersion = "2.0.13";
        public static string longVersion = "2.0.13-20221201-7f1871de";
        public static string buildDate = "20221201";
    }
}
