// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.transport {
    public class VersionInfo {
        public static string appVersion = "2.0.8";
        public static string longVersion = "2.0.8-20220805-1c4337d8";
        public static string buildDate = "20220805";
    }
}
