// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.transport {
    public class VersionInfo {
        public static string appVersion = "2.0.10";
        public static string longVersion = "2.0.10-20221103-db5dab4c";
        public static string buildDate = "20221103";
    }
}
